export const countries = [
  { code: 'US', name: 'United States', dialCode: '+1', emoji: '🇺🇸' },
  { code: 'GB', name: 'United Kingdom', dialCode: '+44', emoji: '🇬🇧' },
  { code: 'CA', name: 'Canada', dialCode: '+1', emoji: '🇨🇦' },
  { code: 'AU', name: 'Australia', dialCode: '+61', emoji: '🇦🇺' },
  { code: 'DE', name: 'Germany', dialCode: '+49', emoji: '🇩🇪' },
  { code: 'FR', name: 'France', dialCode: '+33', emoji: '🇫🇷' },
  { code: 'IN', name: 'India', dialCode: '+91', emoji: '🇮🇳' },
  { code: 'BR', name: 'Brazil', dialCode: '+55', emoji: '🇧🇷' },
  { code: 'ZA', name: 'South Africa', dialCode: '+27', emoji: '🇿🇦' },
  { code: 'JP', name: 'Japan', dialCode: '+81', emoji: '🇯🇵' },
  { code: 'CN', name: 'China', dialCode: '+86', emoji: '🇨🇳' },
  { code: 'RU', name: 'Russia', dialCode: '+7', emoji: '🇷🇺' },
  { code: 'MX', name: 'Mexico', dialCode: '+52', emoji: '🇲🇽' },
  { code: 'ES', name: 'Spain', dialCode: '+34', emoji: '🇪🇸' },
  { code: 'IT', name: 'Italy', dialCode: '+39', emoji: '🇮🇹' },
  { code: 'KR', name: 'South Korea', dialCode: '+82', emoji: '🇰🇷' },
  { code: 'SA', name: 'Saudi Arabia', dialCode: '+966', emoji: '🇸🇦' },
  { code: 'TR', name: 'Turkey', dialCode: '+90', emoji: '🇹🇷' },
  { code: 'ID', name: 'Indonesia', dialCode: '+62', emoji: '🇮🇩' },
  { code: 'AR', name: 'Argentina', dialCode: '+54', emoji: '🇦🇷' },
];